Matthewcurtis1999/vir 1876 setup mypy for virtool core
virtool/virtool-core pull request #174
Opened 2023-09-25 22:13 UTC by mattcurts

config file is currently only set up to ignore missing imports as a means to work around coloredlogs error (will be fixed once merged) and aioredis error which will be addressed later once it is updated to <= 2.0.0.

2023-09-29 18:25 UTC, igboyes requested changes
* For `typing` imports, use `from`. We should all know what these names are without the namespacing.
* Sorry, another deprectation is coming down the Python pipe. They are favouring typing like this `dict[str, int]` instead of `typing.Dict[str, int]`. May as well add this onto your PR.
* You have change to `|` over `Union` and `| None` instead of `Optional` in many places. Be consistent and make all of the changes. There are still lingering `Optional` and `Union` in some spots you touched.

2023-09-29 18:25 UTC, igboyes commented on mypy.ini
> +ignore_missing_imports = True
Why was this necessary?

2023-09-29 18:25 UTC, igboyes commented on pyproject.toml
> +mypy = "^1.5.1"
Install as dev dependency:
```
poetry add mypy --group dev
```

2023-09-29 18:25 UTC, igboyes commented on virtool_core/bio.py
> +async def read_fastq(f) -> typing.AsyncGenerator[tuple, None]:
```suggestion
async def read_fastq(f) -> AsyncGenerator[tuple, None]:
```

2023-09-29 18:25 UTC, igboyes commented on virtool_core/utils.py
> +    command = ["pigz", "-p", processes_str, "-k", "--stdout", abs_path]
Use `pathlib` features.

https://stackoverflow.com/a/44569249
```suggestion
    command = ["pigz", "-p", processes_str, "-k", "--stdout", path.resolve()]
```

2023-09-29 18:25 UTC, igboyes commented on virtool_core/utils.py
> +    processes_str: str = str(processes)
1. Don't use Hungarian notation.
2. Extra variable less clear than just putting type convertion in declaration of `command` list.
```
command = ["pigz", "-p", str(processes), ...]
```

2023-09-29 18:25 UTC, igboyes commented on virtool_core/utils.py
> +    command = ["pigz", "-p", str(processes), "-d", "-k", "--stdout", abs_path]
Same as previous comment on `pathlib`. However, you did convert type inline here!

2023-09-29 18:27 UTC, igboyes commented
The Black formatter is also not running on this PR. The indentation breaks the style in some parts:
```
@asynccontextmanager
async def buffered_bulk_writer(
        collection, batch_size=100, session: Optional[AsyncIOMotorClientSession] = None
):
```

2023-10-03 18:50 UTC, mattcurts commented on mypy.ini
> +ignore_missing_imports = True
This is currently to work around coloredlogs error (will be fixed once merged) and aioredis error which will be addressed later once it is updated to <= 2.0.0.

2023-10-04 18:46 UTC, igboyes approved these changes

2023-10-04 18:48 UTC, merged