Matthewcurtis1999/vir 1974 create a wrapper around reddis client in core
virtool/virtool-core pull request #198
Opened 2024-04-02 20:39 UTC by mattcurts

reverted reddis back to aioredis 1.3 then walked it to reddis 5.0 updating virtool and virtool-workflow along the way.

2024-04-03 18:37 UTC, igboyes requested changes
I'm not sure if this was clear. Since we are doing a bit of an overhaul of how Redis is used in our various repos, it is good to deviate with how things currently are or how things were done because of `aioredis`.

I have included comments will require some major tweaking of how the core is used in `virtool` and `virtool-workflow`.

I am happy to go through this on a call. Let me know.

2024-04-03 18:37 UTC, igboyes commented on virtool_core/redis.py
> +    return Redis.from_url(redis_connection_string, **kwargs)
Is this necessary? I think we could simplify things by getting rid of this.

2024-04-03 18:37 UTC, igboyes commented on virtool_core/redis.py
> +    :param timeout: DEPRECATED: Redis connection timeout
This should just be removed. It will be a breaking change and usages can be updated in the consumers of this package.

2024-04-03 18:37 UTC, igboyes commented on virtool_core/redis.py
> +async def resubscribe(redis: Redis, redis_channel_name: str) -> Channel:
I feel like this could be encapsulated in the wrapper implementation of `subscribe`. This would mean that any subscription started with `Redis.subscribe()` will automatically resubscribe if the connection is broken.

Currently, this is done manually in `virtool`:
https://github.com/virtool/virtool/blob/c621ba6a22bfe3464fe59287337029e42295cfcb/virtool/data/events.py#L214-L223

Reimplement this in the wrapper.

2024-04-03 18:37 UTC, igboyes commented on virtool_core/redis.py
>  async def configure_redis(
Your `Redis` wrapper can actually be written to eliminate this context manager so you end up with something like:
```py
async with Redis(...) as redis:
    ...
```

2024-04-03 18:37 UTC, igboyes commented on virtool_core/redis.py
> +        return (channel,)
There is no point in returning a tuple here since we are only ever subscribing to a singel channel.

The tuple/list was used in `aioredis` because `subscribe()` supported multiple channels being subscribed in one go, which necessitates returning multiple channel objects.

https://aioredis.readthedocs.io/en/v1.3.1/mixins.html#aioredis.commands.PubSubCommandsMixin.subscribe

2024-04-12 18:46 UTC, mattcurts commented on virtool_core/redis.py
> +async def resubscribe(redis: Redis, redis_channel_name: str) -> Channel:
couldn't find an easy way to handle this. main problems include:

- the only way to check if it is still subscribed would be by checking for messages, which consume the messages
- The channel needs to be subscribed to capture the messages which gave me some problems with `` tests/jobs/test_client.py::test_cancel_running``

2024-04-17 16:23 UTC, igboyes submitted a review, later dismissed

2024-04-30 19:25 UTC, igboyes commented
Superseded by #199.

2024-04-30 19:25 UTC, closed without merging